import json
from typing import Dict, Any, List, Tuple
from src.models.workout import WeeklyPlan, DailyPlan, ProposedWorkout

def parse_proposed_workouts_json(json_file_path: str) -> Dict[str, Any]:
    """
    Parses the proposed workouts JSON file and returns a dictionary.
    """
    try:
        with open(json_file_path, 'r') as f:
            data = json.load(f)
        return data
    except FileNotFoundError:
        raise FileNotFoundError(f"File not found: {json_file_path}")
    except json.JSONDecodeError:
        raise ValueError(f"Invalid JSON format in: {json_file_path}")

def process_proposed_workouts(json_file_path: str) -> Tuple[WeeklyPlan, List[DailyPlan], List[ProposedWorkout]]:
    """
    Parses, validates, and processes the proposed workouts JSON file.
    """
    data = parse_proposed_workouts_json(json_file_path)

    weekly_plan = WeeklyPlan(
        weekNumber=data.get('weekNumber'),
        startDate=data.get('startDate'),
        plannedTSS_min=data.get('plannedTSS', {}).get('min'),
        plannedTSS_max=data.get('plannedTSS', {}).get('max'),
        notes=json.dumps(data.get('notes', '')) if isinstance(data.get('notes'), dict) else data.get('notes', '')
    )
    
    daily_plans = []
    proposed_workouts = []

    #daily_plans: List[DailyPlan] = []

    for day in data.get('days', []):
        daily_plan = DailyPlan(
            id=0,  # The ID will be auto-generated by the database
            weekNumber=weekly_plan.weekNumber,
            dayNumber=day.get('dayNumber'),
            date=day.get('date')
        )
        daily_plans.append(daily_plan)

        for workout in day.get('workouts', []):
            proposed_workout = ProposedWorkout(
                id=0,  # The ID will be auto-generated by the database
                dailyPlanId=0,  # The dailyPlanId will be assigned later
                type=workout.get('type'),
                name=workout.get('name'),
                plannedDuration=workout.get('plannedDuration'),
                plannedTSS_min=workout.get('plannedTSS', {}).get('min'),
                plannedTSS_max=workout.get('plannedTSS', {}).get('max'),
                targetRPE_min=workout.get('targetRPE', {}).get('min'),
                targetRPE_max=workout.get('targetRPE', {}).get('max'),
                intervals=json.dumps(workout.get('intervals',[])),
                sections=json.dumps(workout.get('sections',[]))
            )
            # Add a temporary reference to the dayNumber for matching later
            proposed_workout._dayNumber = day.get('dayNumber')  # Temporary attribute
            proposed_workouts.append(proposed_workout)

    return weekly_plan, daily_plans, proposed_workouts